# Generated by Django 5.0.4 on 2024-04-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodelo', '0002_livro_imagem_alter_livro_autor_alter_livro_editora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
    ]
