# Generated by Django 5.0.4 on 2024-04-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodelo', '0003_alter_livro_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='descricao',
            field=models.TextField(default='Descrição padrão', max_length=250),
            preserve_default=False,
        ),
    ]
